<?php

declare(strict_types=1);

namespace App\Catalog;

use App\Spec\DeviceSpec;
use App\Spec\Provenance;

/**
 * Renders the equipment library as a table plus totals.
 *
 * The totals are the practical payoff of keeping weight and dimensions in the specs: they answer
 * "how heavy is the PA" and "what still needs measuring" without opening Blender.
 */
final class CatalogRenderer
{
    private const HEADERS = ['ID', 'Name', 'Category', 'Qty', 'Owner', 'W×H×D (m)', 'kg', 'Σ kg', 'Clone of', 'Provenance'];

    /**
     * @param list<DeviceSpec> $specs
     * @return list<list<string>>
     */
    public function rows(array $specs): array
    {
        $rows = [];
        foreach ($specs as $spec) {
            $rows[] = [
                $spec->id,
                $spec->name,
                $spec->category->value.'/'.$spec->subtype,
                (string)$spec->quantity,
                $spec->owner,
                $this->formatDimensions($spec),
                $this->formatNumber($spec->weightKg),
                $this->formatNumber($spec->totalWeightKg()),
                $spec->originalLabel(),
                $spec->provenance->label(),
            ];
        }

        return $rows;
    }

    /**
     * @return list<string>
     */
    public function headers(): array
    {
        return self::HEADERS;
    }

    /**
     * @param list<DeviceSpec> $specs
     * @return array{
     *     devices: int,
     *     units: int,
     *     total_weight_kg: float,
     *     total_volume_m3: float,
     *     by_category: array<string, int>,
     *     by_owner: array<string, array{units: int, weight_kg: float}>,
     *     unmeasured: int,
     *     unmeasured_ids: list<string>,
     *     dimensions_unmeasured_ids: list<string>,
     *     weight_unmeasured_ids: list<string>
     * }
     */
    public function summary(array $specs): array
    {
        $units = 0;
        $weight = 0.0;
        $volume = 0.0;
        $byCategory = [];
        $byOwner = [];
        $unmeasuredIds = [];
        $dimensionsUnmeasured = [];
        $weightUnmeasured = [];

        foreach ($specs as $spec) {
            $units += $spec->quantity;
            $weight += $spec->totalWeightKg();
            $volume += $spec->dimensions->volumeM3() * $spec->quantity;
            $byCategory[$spec->category->value] = ($byCategory[$spec->category->value] ?? 0) + $spec->quantity;

            $owner = $byOwner[$spec->owner] ?? ['units' => 0, 'weight_kg' => 0.0];
            $byOwner[$spec->owner] = [
                'units' => $owner['units'] + $spec->quantity,
                'weight_kg' => $owner['weight_kg'] + $spec->totalWeightKg(),
            ];

            if (!$spec->provenance->isFullyMeasured()) {
                $unmeasuredIds[] = $spec->id;
            }
            if (!$spec->provenance->dimensions->isMeasured()) {
                $dimensionsUnmeasured[] = $spec->id;
            }
            if (!$spec->provenance->weight->isMeasured()) {
                $weightUnmeasured[] = $spec->id;
            }
        }
        ksort($byCategory);
        ksort($byOwner);

        return [
            'devices' => count($specs),
            'units' => $units,
            'total_weight_kg' => $weight,
            'total_volume_m3' => $volume,
            'by_category' => $byCategory,
            'by_owner' => $byOwner,
            'unmeasured' => count($unmeasuredIds),
            'unmeasured_ids' => $unmeasuredIds,
            'dimensions_unmeasured_ids' => $dimensionsUnmeasured,
            'weight_unmeasured_ids' => $weightUnmeasured,
        ];
    }

    /**
     * Markdown for `docs/catalog.md`. Generated, so it carries a header saying so — nobody should
     * be editing it by hand when the specs are the source of truth.
     *
     * @param list<DeviceSpec> $specs
     */
    public function renderMarkdown(array $specs): string
    {
        $lines = [
            '# Equipment catalog',
            '',
            'Generated by `bin/console catalog --write`. Do not edit — the spec files under'
                .' [`specs/`](../specs) are the source of truth.',
            '',
        ];

        if ($specs === []) {
            $lines[] = 'No specs yet.';

            return implode("\n", $lines)."\n";
        }

        $lines[] = '| '.implode(' | ', self::HEADERS).' |';
        $lines[] = '|'.str_repeat('---|', count(self::HEADERS));
        foreach ($this->rows($specs) as $row) {
            $lines[] = '| '.implode(' | ', $row).' |';
        }

        $summary = $this->summary($specs);
        $lines[] = '';
        $lines[] = '## Totals';
        $lines[] = '';
        $lines[] = sprintf('- Devices: %d (%d units)', $summary['devices'], $summary['units']);
        $lines[] = sprintf('- Total weight: %s kg', $this->formatNumber($summary['total_weight_kg']));
        $lines[] = sprintf('- Total volume: %s m³', $this->formatNumber($summary['total_volume_m3'], 3));
        foreach ($summary['by_category'] as $category => $count) {
            $lines[] = sprintf('- %s: %d units', ucfirst($category), $count);
        }
        foreach ($summary['by_owner'] as $owner => $totals) {
            $lines[] = sprintf(
                '- Owner %s: %d units, %s kg',
                $owner,
                $totals['units'],
                $this->formatNumber($totals['weight_kg']),
            );
        }
        $lines[] = sprintf(
            '- Dimensions measured: %d of %d%s',
            $summary['devices'] - count($summary['dimensions_unmeasured_ids']),
            $summary['devices'],
            $summary['dimensions_unmeasured_ids'] === []
                ? ''
                : ' — open: '.implode(', ', $summary['dimensions_unmeasured_ids']),
        );
        $lines[] = sprintf(
            '- Weights measured: %d of %d%s',
            $summary['devices'] - count($summary['weight_unmeasured_ids']),
            $summary['devices'],
            $summary['weight_unmeasured_ids'] === []
                ? ''
                : ' — open: '.implode(', ', $summary['weight_unmeasured_ids']),
        );
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param list<DeviceSpec> $specs
     * @return list<DeviceSpec> specs with anything still not measured on the actual cabinet
     */
    public function unmeasured(array $specs): array
    {
        return array_values(array_filter(
            $specs,
            static fn (DeviceSpec $spec): bool => !$spec->provenance->isFullyMeasured(),
        ));
    }

    private function formatDimensions(DeviceSpec $spec): string
    {
        return sprintf(
            '%s × %s × %s',
            $this->formatNumber($spec->dimensions->width, 3),
            $this->formatNumber($spec->dimensions->height, 3),
            $this->formatNumber($spec->dimensions->depth, 3),
        );
    }

    /**
     * Trailing zeros are noise in a table, so they go — 0.60 reads as 0.6, 34.0 as 34.
     */
    private function formatNumber(float $value, int $decimals = 1): string
    {
        $formatted = number_format($value, $decimals, '.', '');

        return str_contains($formatted, '.')
            ? rtrim(rtrim($formatted, '0'), '.')
            : $formatted;
    }
}
