<?php

declare(strict_types=1);

namespace App\Tests\Scene;

use App\Scene\GeneratedHeader;
use App\Scene\GeneratedSceneDiff;
use PHPUnit\Framework\TestCase;

/**
 * The before/after count `scene:diff` prints, on headers shaped the way {@see \App\Scene\StackSceneWriter} writes them.
 */
final class GeneratedSceneDiffTest extends TestCase
{
    public function testTheHeaderGivesTheVerdictTheRowsAndEachStacksMiss(): void
    {
        $header = GeneratedHeader::parse('gmss/stacked-2-pooled-center-low-----possible.yaml', self::scene(['2× skram', '3× turbo-top'], 2.963, 2.0, 1.75));

        self::assertNotNull($header);
        self::assertSame('gmss/stacked-2-pooled-center-low----', $header->key);
        self::assertSame('gmss', $header->folder);
        self::assertTrue($header->possible);
        self::assertSame(['2× skram', '3× turbo-top'], $header->rows);
        // 2.963 m of subs against a stated 1.75 m target.
        self::assertEqualsWithDelta([1.213], $header->misses, 1e-9);
    }

    /** No `target_sub_height_m` in the stack means the default 2.5 m. */
    public function testAnUnstatedTargetIsTheDefault(): void
    {
        $header = GeneratedHeader::parse('gmss/a-impossible.yaml', self::scene(['1× nuke'], 2.2, 2.0, null));

        self::assertNotNull($header);
        self::assertFalse($header->possible);
        self::assertEqualsWithDelta([0.3], $header->misses, 1e-9);
    }

    public function testAFileWithoutAVerdictIsNoGeneratedRig(): void
    {
        self::assertNull(GeneratedHeader::parse('gmss/README.yaml', "id: x\n"));
    }

    /** A changed verdict renames the file, and the rig is still matched as one. */
    public function testARenamedVerdictIsOneRigThatTurnedPossible(): void
    {
        $before = self::headers([
            'gmss/a-impossible.yaml' => self::scene(['1× nuke'], 2.2, 2.0, null),
            'gmss/b-possible.yaml' => self::scene(['1× skram'], 2.4, 2.0, null),
            'gmss/gone-possible.yaml' => self::scene(['1× skram'], 2.4, 2.0, null),
        ]);
        $after = self::headers([
            'gmss/a-possible.yaml' => self::scene(['1× nuke'], 2.2, 2.0, null),
            'gmss/b-possible.yaml' => self::scene(['2× skram'], 2.5, 2.0, null),
            'gmss/new-possible.yaml' => self::scene(['1× skram'], 2.4, 2.0, null),
        ]);

        $folders = GeneratedSceneDiff::compare($before, $after);

        self::assertSame(['gmss'], array_keys($folders));
        $gmss = $folders['gmss'];
        self::assertSame([2, 3], $gmss['possible']);
        self::assertSame([1, 0], $gmss['impossible']);
        self::assertSame(['gmss/a'], $gmss['to_possible']);
        self::assertSame([], $gmss['to_impossible']);
        self::assertSame(['gmss/new'], $gmss['appeared']);
        self::assertSame(['gmss/gone'], $gmss['vanished']);
        self::assertSame(['gmss/b'], $gmss['rows_changed']);
        // 0.3 + 0.1 + 0.1 before, and 0.3 + 0.0 + 0.1 after.
        self::assertEqualsWithDelta(0.5, $gmss['miss_m'][0], 1e-9);
        self::assertEqualsWithDelta(0.4, $gmss['miss_m'][1], 1e-9);
    }

    public function testAnUnchangedFolderIsLeftOut(): void
    {
        $same = self::headers(['gmss/a-possible.yaml' => self::scene(['1× nuke'], 2.2, 2.0, null)]);

        self::assertSame([], GeneratedSceneDiff::compare($same, $same));
        self::assertSame(['gmss'], array_keys(GeneratedSceneDiff::compare($same, $same, everyFolder: true)));
    }

    /**
     * @param array<string, string> $texts
     *
     * @return array<string, GeneratedHeader>
     */
    private static function headers(array $texts): array
    {
        $headers = [];
        foreach ($texts as $path => $text) {
            $header = GeneratedHeader::parse($path, $text);
            self::assertNotNull($header);
            $headers[$path] = $header;
        }

        return $headers;
    }

    /** @param list<string> $rows */
    private static function scene(array $rows, float $subs, float $interface, ?float $target): string
    {
        $lines = ['# Generated by `bin/console scene:stack` — edit it freely, it is an ordinary scene file.', '#', '# What it deals out today:', '#'];
        foreach ($rows as $index => $row) {
            $lines[] = sprintf('#   %d  %-70s %8s m wide', $index + 1, $row, '1.2');
        }
        $lines[] = '#';
        $lines[] = sprintf('# Subs reach %s m against a %s m interface. The stack is 3.0 m of cabinet.', $subs, $interface);
        $lines[] = '#';
        $lines[] = 'id: x';
        $lines[] = 'placements:';
        $lines[] = '  - id: main';
        $lines[] = '    at: [0.0, 0.0]';
        $lines[] = '    stack:';
        $lines[] = "      interface_height_m: {$interface}";
        if (null !== $target) {
            $lines[] = "      target_sub_height_m: {$target}";
        }

        return implode("\n", $lines)."\n";
    }
}
