<?php

declare(strict_types=1);

namespace App\Scene;

/**
 * What a row of turned cabinets does with the odd one out.
 *
 * {@see Tier::mirrored} splits a rolled row about its own centre so the left half gets the mirror image of the right
 * half's quarter turn — which is what makes a turned wall symmetric about the rig's centre line instead of having
 * every horn mouth face the same way. An **odd** count cannot be halved, so one cabinet has to break the symmetry,
 * and there is no arrangement that avoids it: the middle cabinet must roll one way or the other.
 *
 * Three answers, and none is free:
 *
 * * **{@see Alternate}** — accept the imbalance per row and cancel it across the stack, by flipping which side gets
 *   the extra on each successive row. A row of five is 2 + 3, the row above it 3 + 2, and the wall comes out even
 *   overall. Nothing changes height, nothing new can fail.
 * * **{@see Centred}** — leave the middle cabinet standing, so a row of five is 2 rolled left, 1 upright, 2 rolled
 *   right: genuinely symmetric row by row. The cost is real and geometric — a Flexy on its side is 591 mm tall and
 *   763 upright, so that cabinet stands 172 mm proud and whatever sits on the row has to bridge the step. Expect
 *   {@see StackSolver::swallows} and {@see StackChecks::bearingProblems} to refuse it wherever something does, which
 *   is most places; a top row is where it builds.
 * * **{@see Column}** — send the extra to the same side on every row, so the spares line up as one straight column from
 *   floor to top. The stack is then lopsided by one cabinet overall, which {@see Alternate} spends its zig-zag to
 *   avoid, and in exchange nothing zig-zags: every row is built to one rule, and the seam between the two mirrored
 *   halves runs straight up the wall. Same heights as `alternate`, so unlike `centred` it introduces no step and
 *   nothing new can fail on it.
 *
 * **`Centred` was called `upright` and the rename is not cosmetic.** The sweep now has an *orientation* axis whose own
 * values include `upright`, meaning nothing is rolled, so a file called `stacked-gmss-1-turned-upright-center` read as
 * a contradiction — "every sub turned, nothing rolled". `centred` also says what the style does.
 *
 * All three are generated by default and `deduplicate()` drops whichever makes no difference, so the choice only costs
 * a file where a rolled row actually has an **odd** count — measured at 8 such rows across 4 scenes, so most of this
 * axis is absorbed rather than written.
 */
enum MirrorStyle: string
{
    /** The odd cabinet goes to one side, and the next row up sends it to the other. */
    case Alternate = 'alternate';

    /** The odd cabinet stays standing in the middle: symmetric row, 172 mm step. */
    case Centred = 'centred';

    /** The odd cabinet goes to the same side on every row: one straight seam, one lopsided stack. */
    case Column = 'column';
}
