<?php

declare(strict_types=1);

namespace App\Scene;

/**
 * What a row of turned cabinets does with the odd one out.
 *
 * {@see Tier::mirrored} splits a rolled row about its own centre so the left half gets the mirror image of the right
 * half's quarter turn — which is what makes a turned wall symmetric about the rig's centre line instead of having
 * every horn mouth face the same way. An **odd** count cannot be halved, so one cabinet has to break the symmetry,
 * and there is no arrangement that avoids it: the middle cabinet must roll one way or the other.
 *
 * Two answers, and neither is free:
 *
 * * **{@see Alternate}** — accept the imbalance per row and cancel it across the stack, by flipping which side gets
 *   the extra on each successive row. A row of five is 2 + 3, the row above it 3 + 2, and the wall comes out even
 *   overall. Nothing changes height, nothing new can fail.
 * * **{@see Upright}** — leave the middle cabinet standing, so a row of five is 2 rolled left, 1 upright, 2 rolled
 *   right: genuinely symmetric row by row. The cost is real and geometric — a Flexy on its side is 591 mm tall and
 *   763 upright, so that cabinet stands 172 mm proud and whatever sits on the row has to bridge the step. Expect
 *   {@see StackSolver::swallows} and {@see StackChecks::bearingProblems} to refuse it wherever something does, which
 *   is most places; a top row is where it builds.
 *
 * Both are generated by default and `deduplicate()` drops whichever makes no difference, so the choice only costs a
 * file where a rolled row actually has an odd count — four of the thirty-odd generated scenes.
 */
enum MirrorStyle: string
{
    /** The odd cabinet goes to one side, and the next row up sends it to the other. */
    case Alternate = 'alternate';

    /** The odd cabinet stays upright in the middle: symmetric row, 172 mm step. */
    case Upright = 'upright';
}
