<?php

declare(strict_types=1);

namespace App\Scene;

/**
 * What silhouette a solved stack is allowed to have.
 *
 * The bearing rule permits a row to be *wider* than the one carrying it — two thirds of a cabinet past each end,
 * derived in {@see StackSolver::OVERHANG_PER_SIDE} — and for a long time nothing said it should not be. That is how
 * five of the twelve generated stacks came out with their rows widening as they rose: 1.34 m on the floor under
 * 1.82, 1.84, 2.32, 2.18 and 2.51 m. Every one of those rows is legally carried and the rig reads top-heavy, a V
 * balanced on its point rather than a wall.
 *
 * * **{@see Pyramid}** — no row wider than the row below it. What a crew builds, and what makes a stack *shorter*
 *   as well as better-looking: the taper only pays off if the bottom row is packed as wide as the stage allows, and
 *   a wide base is exactly what needs fewer rows above it.
 * * **{@see Free}** — as wide as the bearing rule allows, which is what the solver did before this existed. Kept
 *   because it is occasionally the only arrangement that stands up at all: a stack whose deepest cabinets are few
 *   and narrow has no wide base available, and forbidding growth there refuses the rig rather than improving it.
 *
 * Both are generated by default, one scene each, the way `--align` already writes one scene per layout mode.
 */
enum StackShape: string
{
    /** Rows non-increasing in width from the floor up. */
    case Pyramid = 'pyramid';

    /** Rows as wide as {@see Gravity::MIN_BEARING} allows, growing upward if that is what fits. */
    case Free = 'free';
}
