<?php

declare(strict_types=1);

namespace App\Scene;

/**
 * Turns a solved {@see Stack} into a scene file somebody can read, edit and argue with.
 *
 * Hand-rolled rather than `Yaml::dump()`, and the reason is the comments. Every scene in this repository
 * explains itself — which cabinet went where and *why that number* — and a generated one that arrived as a
 * bare mapping would be the only magic file in the folder. So the header carries the solved tier table, the
 * widths, the interface height it reached and anything the solver warned about, which is what makes the
 * output reviewable instead of trusted.
 *
 * The body is emitted as a `stack:` block rather than as the expanded tiers, deliberately: the whole point of
 * the feature is that the rig follows the specs, so a generated scene has to re-solve when a cabinet is
 * finally measured rather than freeze today's answer into a list of rows.
 */
final class StackSceneWriter
{
    /**
     * @param list<Tier> $tiers the solve, for the header only
     * @param list<string> $warnings what the solver had to say, for the header only
     * @param array{float, float} $at
     * @param list<string> $from device ids in the stack, low frequency first
     */
    public static function yaml(
        string $id,
        string $name,
        Stack $stack,
        array $tiers,
        array $warnings,
        array $at,
        array $from,
        ?LayoutMode $align = null,
    ): string {
        $lines = self::header($stack, $tiers, $warnings, $align);

        $lines[] = sprintf('id: %s', $id);
        $lines[] = sprintf('name: %s', self::quote($name));
        $lines[] = '';
        $lines[] = 'focus:';
        $lines[] = '  far:';
        $lines[] = '    distance_m: 10.0';
        $lines[] = '    height_m: 1.8';
        $lines[] = '  near:';
        $lines[] = '    distance_m: 2.0';
        $lines[] = '    height_m: 1.8';
        $lines[] = '';
        $lines[] = 'placements:';
        $lines[] = '  - id: main';
        $lines[] = sprintf('    at: [%s, %s]', self::number($at[0]), self::number($at[1]));
        $lines[] = '    aim: far                 # the TOP tiers only; subs fire straight ahead';

        if ($align !== null) {
            $lines[] = '    align:';
            $lines[] = sprintf('      mode: %s', $align->value);
        }

        $lines[] = '    stack:';
        foreach (self::constraints($stack) as $key => $value) {
            $lines[] = sprintf('      %s: %s', $key, self::number($value));
        }
        $lines[] = '      from:';
        foreach ($from as $deviceId) {
            $lines[] = sprintf('        - %s', $deviceId);
        }

        $lines[] = '';

        return implode("\n", $lines)."\n";
    }


    /**
     * The explaining comment block — the whole reason this is not `Yaml::dump()`.
     *
     * @param list<Tier> $tiers
     * @param list<string> $warnings
     * @return list<string>
     */
    private static function header(
        Stack $stack,
        array $tiers,
        array $warnings,
        ?LayoutMode $align,
    ): array {
        $lines = [
            '# Generated by `bin/console scene:stack` — edit it freely, it is an ordinary scene file.',
            '#',
            '# Nothing here says which cabinet goes in which row. The constraints below do, and the compiler',
            '# re-solves them every build, so the rig follows the specs when a cabinet is finally measured.',
            '#',
            '# What it deals out today:',
            '#',
        ];

        $height = 0.0;
        $subHeight = 0.0;
        foreach ($tiers as $index => $tier) {
            $height += $tier->heightM();
            if ($tier->isSub()) {
                $subHeight += $tier->heightM();
            }
            $lines[] = sprintf(
                '#   %d  %-70s %8s m wide',
                $index + 1,
                $tier->label(),
                self::number(round($tier->widthM($stack->gapM), 4)),
            );
        }

        $lines[] = '#';
        $lines[] = sprintf(
            '# Subs reach %s m, so the tops clear the %s m interface. The stack is %s m of cabinet.',
            self::number(round($subHeight, 3)),
            self::number($stack->interfaceHeightM),
            self::number(round($height, 3)),
        );

        if ($align !== null) {
            $lines[] = sprintf(
                '# `align: %s` spreads the top tier onto the edges of the row carrying it.',
                $align->value,
            );
        }
        if ($warnings !== []) {
            $lines[] = '#';
            $lines[] = '# The build report will warn about this, and both are real:';
            foreach ($warnings as $warning) {
                foreach (self::wrap('#   * '.$warning, 118) as $wrapped) {
                    $lines[] = $wrapped;
                }
            }
        }

        return $lines;
    }

    /**
     * @return array<string, float>
     */
    private static function constraints(Stack $stack): array
    {
        $constraints = ['interface_height_m' => $stack->interfaceHeightM, 'gap_m' => $stack->gapM];
        foreach (['max_width_m' => $stack->maxWidthM, 'min_width_m' => $stack->minWidthM, 'max_height_m' => $stack->maxHeightM] as $key => $value) {
            if ($value !== null) {
                $constraints = [$key => $value] + $constraints;
            }
        }

        return $constraints;
    }

    /**
     * @return list<string>
     */
    private static function wrap(string $text, int $width): array
    {
        $wrapped = explode("\n", wordwrap($text, $width, "\n"));

        return array_map(
            static fn (int $index, string $line): string => $index === 0 ? $line : '#     '.ltrim($line, '# '),
            array_keys($wrapped),
            $wrapped,
        );
    }

    /** Numbers that read like the ones in a hand-written scene: `0.02`, `3.7`, `2.0` — never `2.0000000001`. */
    private static function number(float $value): string
    {
        $formatted = rtrim(rtrim(sprintf('%.4F', $value), '0'), '.');

        return $formatted === '' || $formatted === '-' ? '0.0' : (str_contains($formatted, '.') ? $formatted : $formatted.'.0');
    }

    private static function quote(string $value): string
    {
        return '"'.str_replace('"', '\"', $value).'"';
    }
}
