"""Assemble the Blender asset library from the per-device .blend files.

Invoked by the PHP CLI:

    blender --background --factory-startup --python blender/build_library.py -- --plan build/plans/_library.json

Every device becomes a collection asset, so dragging it out of the Asset Browser brings the whole
cabinet at true scale, already sitting on the floor. The devices are also instanced in a row, which
makes the library file double as a visual overview of the gear.
"""

import os
import sys
import uuid

import bpy

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lib import export  # noqa: E402  (must follow the sys.path fix)

# Gap between devices in the overview row.
_SPACING = 0.4

_CATALOG_ROOT = "SdWa5"

# Fixed namespace so catalog UUIDs are stable across rebuilds — a changing UUID would detach
# every asset from its catalog each time the library is regenerated.
_CATALOG_NAMESPACE = uuid.UUID("6f9619ff-8b86-d011-b42d-00c04fc964ff")


def _catalog_id(path):
    return str(uuid.uuid5(_CATALOG_NAMESPACE, path))


def _write_catalog_file(directory, catalogs):
    """Blender stores asset catalogs in a sidecar file next to the .blend."""
    lines = [
        "# This is an Asset Catalog Definition file for Blender.",
        "# Generated by sdwa5-3d — do not edit.",
        "",
        "VERSION 1",
        "",
    ]
    for path in sorted(catalogs):
        lines.append("%s:%s:%s" % (_catalog_id(path), path, path.replace("/", "-")))

    target = os.path.join(directory, "blender_assets.cats.txt")
    with open(target, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def _append_collection(blend_path, device_id):
    with bpy.data.libraries.load(blend_path, link=False) as (data_from, data_to):
        if device_id not in data_from.collections:
            raise SystemExit(
                "sdwa5-3d: %s contains no collection named %r — rebuild the model"
                % (blend_path, device_id)
            )
        data_to.collections = [device_id]

    return data_to.collections[0]


def build(plan):
    export.reset_scene()

    catalogs = set()
    offset = 0.0

    for device in plan["devices"]:
        collection = _append_collection(device["blend"], device["id"])

        catalog_path = "%s/%s" % (_CATALOG_ROOT, device["category"].capitalize())
        catalogs.add(catalog_path)

        collection.asset_mark()
        asset = collection.asset_data
        # Only the id is writable — Blender resolves the display name from the sidecar catalog
        # file written at the end of this build.
        asset.catalog_id = _catalog_id(catalog_path)
        asset.description = "%s — %s/%s, %s" % (
            device["name"],
            device["category"],
            device["subtype"],
            device["provenance"],
        )
        for tag in (device["category"], device["subtype"], device["provenance"]):
            asset.tags.new(tag)

        # The asset flag alone does not keep an unlinked collection alive through a save.
        collection.use_fake_user = True

        width = float(device.get("width_m") or 1.0)
        instance = bpy.data.objects.new(device["id"], None)
        instance.instance_type = "COLLECTION"
        instance.instance_collection = collection
        instance.location = (offset + width / 2.0, 0.0, 0.0)
        bpy.context.scene.collection.objects.link(instance)
        offset += width + _SPACING

    output = plan["output"]
    export.save_blend(output)
    _write_catalog_file(os.path.dirname(output), catalogs)

    print("sdwa5-3d: library with %d device(s) → %s" % (len(plan["devices"]), output))


if __name__ == "__main__":
    build(export.parse_plan_argument(list(sys.argv)))
