<?php

declare(strict_types=1);

namespace App\Load;

/**
 * Writes a load plan out as a scene: the convoy standing in a row with each vehicle's load inside it.
 *
 * **A scene file, so the pack goes through the same pipeline as everything else** — `scene:build` assembles it,
 * `scene:render` draws it, and the geometry checks in `ShippedScenesTest` sweep it for cabinets inside each other
 * exactly as they do a rig. That is worth more than a bespoke renderer would be: if the layout rule produces two
 * cabinets in the same place, the repository's own checks say so rather than the picture merely looking odd.
 *
 * **No z is written, which is the same discipline every other scene follows.** A stacked unit says `on:` and names
 * the cabinet beneath it, so the height comes from that cabinet's spec — measure a Flexy and every pack corrects
 * itself. What `at:` carries is x and y only, and the compiler takes z from the support's top face.
 *
 * **The convoy is nose to tail with a stated gap**, which is a diagram rather than a claim about a car park.
 */
final class PackSceneWriter
{
    /** Air between vehicles, so the three read as three rather than as one long shed. */
    private const CONVOY_GAP_M = 1.5;

    /**
     * @param list<LoadPlan> $plans
     * @param list<array{spec: \App\Spec\DeviceSpec, count: int}> $leftovers
     */
    public function yaml(string $id, array $plans, array $leftovers): string
    {
        $layout = new PackLayout();
        $lines = [
            '# Generated by `bin/console scene:pack` — the load plan as a picture.',
            '#',
            '# **THE POSITIONS ARE ONE STATED RULE, NOT AN OPTIMAL PACK.** Heaviest first onto the bay floor in rows,',
            '# then columns on top of whatever can hold them, nothing rotated and nothing interleaved. A real pack is',
            '# tighter. See `App\\Load\\PackLayout` for the rule and what it ignores.',
            '#',
            '# Regenerate it with:',
            '#',
            '#   bin/console scene:pack --write',
            '#',
        ];

        $overflowNotes = [];
        $placements = [];
        $offset = 0.0;

        foreach ($plans as $plan) {
            $vehicle = $plan->vehicle;
            $half = $vehicle->dimensions->depth / 2.0;
            $offset += $half;

            $lines[] = sprintf(
                '# %s — %.1f kg of %.1f kg payload, %d units',
                $vehicle->id,
                $plan->weightKg(),
                $plan->payloadKg,
                $plan->units(),
            );

            $placements[] = sprintf("  - id: %s\n    device: %s\n    at: [ %s, %s ]", $vehicle->id, $vehicle->id, self::number(0.0), self::number($offset));

            ['placed' => $placed, 'overflow' => $overflow] = $layout->forPlan($plan);
            foreach ($placed as $entry) {
                $block = sprintf(
                    "  - id: %s\n    device: %s\n    at: [ %s, %s ]",
                    $entry['id'],
                    $entry['device']->id,
                    self::number($entry['at'][0]),
                    self::number($offset + $entry['at'][1]),
                );
                if ($entry['on'] !== null) {
                    $block .= sprintf("\n    on: %s", $entry['on']);
                }
                $placements[] = $block;
            }

            foreach ($overflow as $spec) {
                $overflowNotes[] = sprintf('%s has no room left in %s', $spec->id, $vehicle->id);
            }

            // **A unit taller than the vehicle is drawn standing, because the rule does not rotate anything.** The
            // render is what found this: `truss-tower-4m` is 4 m tall and came out as a mast sticking out of a 1 m
            // trailer. That is honest about the rule and misleading about the load, so the file names it — a reader
            // should not have to notice a spike in a picture to learn that something has to be laid down.
            //
            // **Over what was placed, not over what was assigned**, and once per device. Reading `$plan->items`
            // instead named both scaffold towers as drawn standing when the rule had not placed either of them —
            // a warning about a spike that is not in the picture is worse than no warning.
            $tallNoted = [];
            foreach ($placed as ['device' => $spec]) {
                if (isset($tallNoted[$spec->id])) {
                    continue;
                }
                if ($spec->dimensions->height <= $vehicle->dimensions->height + 1e-9) {
                    continue;
                }
                $tallNoted[$spec->id] = true;
                // **An open bed has no roof, so "too tall for the vehicle" is not the same statement there.** A
                // generator standing 1.2 m on a 1 m trailer is perfectly normal and the first wording called it
                // something that would have to be laid down, which is simply false. A 4 m mast on the same trailer
                // is still worth naming — so the note says what it can see and leaves the judgement to the reader.
                $overflowNotes[] = $vehicle->vehicle?->loadBay === null
                    ? sprintf(
                        '%s stands %.3f m proud on %s, an open bed with no roof to check it against',
                        $spec->id,
                        $spec->dimensions->height,
                        $vehicle->id,
                    )
                    : sprintf(
                        '%s is %.3f m tall against a %.3f m bay in %s — drawn standing, and it would have to be'
                        .' laid down',
                        $spec->id,
                        $spec->dimensions->height,
                        $vehicle->vehicle->loadBay->height,
                        $vehicle->id,
                    );
            }

            $offset += $half + self::CONVOY_GAP_M;
        }

        $lines[] = '#';
        $lines[] = 'id: '.$id;
        $lines[] = 'name: "Packed convoy"';
        $lines[] = '';
        $lines[] = 'placements:';

        $notes = [];
        if ($leftovers !== []) {
            $notes[] = 'NOT CARRIED AT ALL — the fleet has no legal room for these:';
            foreach ($leftovers as ['spec' => $spec, 'count' => $count]) {
                $notes[] = sprintf('  %d × %s (%.1f kg)', $count, $spec->id, $spec->weightKg * $count);
            }
        }
        if ($overflowNotes !== []) {
            $notes[] = '';
            $notes[] = 'WHAT THE LAYOUT RULE CANNOT DO, which is a statement about the rule rather than about the';
            $notes[] = 'vans — a tighter pack, or one that turned things over, would handle these:';
            foreach ($overflowNotes as $note) {
                $notes[] = '  '.$note;
            }
        }

        $yaml = implode("\n", $lines)."\n".implode("\n\n", $placements)."\n";
        if ($notes !== []) {
            $yaml .= "\nnotes: |\n".implode("\n", array_map(static fn (string $n): string => '  '.$n, $notes))."\n";
        }

        return $yaml;
    }

    private static function number(float $value): string
    {
        $formatted = rtrim(rtrim(sprintf('%.4F', $value), '0'), '.');

        return $formatted === '' || $formatted === '-0' ? '0' : $formatted;
    }
}
