<?php

declare(strict_types=1);

namespace App\Load;

/**
 * Writes a load plan out as a scene: the convoy standing in a row with each vehicle's load inside it.
 *
 * **A scene file, so the pack goes through the same pipeline as everything else** — `scene:build` assembles it,
 * `scene:render` draws it, and the geometry checks in `ShippedScenesTest` sweep it for cabinets inside each other
 * exactly as they do a rig. That is worth more than a bespoke renderer would be: if the layout rule produces two
 * cabinets in the same place, the repository's own checks say so rather than the picture merely looking odd.
 *
 * **No z is written, which is the same discipline every other scene follows.** A stacked unit says `on:` and names
 * the cabinet beneath it, so the height comes from that cabinet's spec — measure a Flexy and every pack corrects
 * itself. What `at:` carries is x and y only, and the compiler takes z from the support's top face.
 *
 * **The convoy is nose to tail with a stated gap**, which is a diagram rather than a claim about a car park.
 */
final class PackSceneWriter
{
    /** Air between vehicles, so the three read as three rather than as one long shed. */
    private const CONVOY_GAP_M = 1.5;

    /**
     * @param list<LoadPlan> $plans
     * @param list<array{spec: \App\Spec\DeviceSpec, count: int}> $leftovers
     */
    public function yaml(string $id, array $plans, array $leftovers): string
    {
        $layout = new PackLayout();
        $lines = [
            '# Generated by `bin/console scene:pack` — the load plan as a picture.',
            '#',
            '# **THE POSITIONS ARE ONE STATED RULE, NOT AN OPTIMAL PACK.** Heaviest first onto the bay floor in rows,',
            '# then columns on top of whatever can hold them, a unit turned only when it does not fit as it stands, and',
            '# nothing interleaved. A real pack is tighter. See `App\\Load\\PackLayout` for the rule and what it ignores.',
            '#',
            '# Regenerate it with:',
            '#',
            '#   bin/console scene:pack --owner=sdwa5 --owner=sepp --write',
            '#',
        ];

        $overflowNotes = [];
        $placements = [];
        $offset = 0.0;

        foreach ($plans as $plan) {
            $vehicle = $plan->vehicle;
            $half = $vehicle->dimensions->depth / 2.0;
            $offset += $half;

            $lines[] = sprintf(
                '# %s — %.1f kg of %.1f kg payload, %d units',
                $vehicle->id,
                $plan->weightKg(),
                $plan->payloadKg,
                $plan->units(),
            );

            $placements[] = sprintf("  - id: %s\n    device: %s\n    at: [ %s, %s ]", $vehicle->id, $vehicle->id, self::number(0.0), self::number($offset));

            ['placed' => $placed, 'overflow' => $overflow] = $layout->forPlan($plan);
            foreach ($placed as $entry) {
                $block = sprintf(
                    "  - id: %s\n    device: %s\n    at: [ %s, %s ]",
                    $entry['id'],
                    $entry['device']->id,
                    self::number($entry['at'][0]),
                    self::number($offset + $entry['at'][1]),
                );
                if (null !== $entry['on']) {
                    $block .= sprintf("\n    on: %s", $entry['on']);
                }
                // A turned unit, about its own origin, which is why `at` is not the middle of the space it fills.
                foreach (['pitch_deg' => $entry['turn']->pitchDeg, 'roll_deg' => $entry['turn']->rollDeg, 'yaw_deg' => $entry['turn']->yawDeg] as $key => $angle) {
                    if (0.0 !== $angle) {
                        $block .= sprintf("\n    %s: %s", $key, self::number($angle));
                    }
                }
                // The device in its packed form, so the scene compiles and draws the transport box.
                if ($entry['device']->folded) {
                    $block .= "\n    packed: true";
                }
                $placements[] = $block;
            }

            foreach ($overflow as $spec) {
                $overflowNotes[] = sprintf('%s has no room left in %s', $spec->id, $vehicle->id);
            }

            // **An open bed has no roof, so a unit standing taller than the vehicle is named rather than refused.**
            // A generator standing 1.2 m on a 1 m trailer is perfectly normal, and the note says what it can see and
            // leaves the judgement to the reader. Inside a bay the layout never lets a unit reach the roof, so there is
            // nothing to name.
            //
            // **Over what was placed, not over what was assigned**, and once per device, with the height the unit
            // has once turned. A warning about a spike that is not in the picture is worse than no warning.
            $tallNoted = [];
            if (null === $vehicle->vehicle?->loadBay) {
                foreach ($placed as ['device' => $spec, 'box' => $box]) {
                    $height = $box['max'][2] - $box['min'][2];
                    if (isset($tallNoted[$spec->id]) || $height <= $vehicle->dimensions->height + 1e-9) {
                        continue;
                    }
                    $tallNoted[$spec->id] = true;
                    $overflowNotes[] = sprintf(
                        '%s stands %.3f m proud on %s, an open bed with no roof to check it against',
                        $spec->id,
                        $height,
                        $vehicle->id,
                    );
                }
            }

            $offset += $half + self::CONVOY_GAP_M;
        }

        $lines[] = '#';
        $lines[] = 'id: '.$id;
        $lines[] = 'name: "Packed convoy"';
        $lines[] = '';
        $lines[] = 'placements:';

        $notes = [];
        if ([] !== $leftovers) {
            $notes[] = 'NOT CARRIED AT ALL — the fleet has no legal room for these:';
            foreach ($leftovers as ['spec' => $spec, 'count' => $count]) {
                $notes[] = sprintf('  %d × %s (%.1f kg)', $count, $spec->id, $spec->weightKg * $count);
            }
        }
        if ([] !== $overflowNotes) {
            $notes[] = '';
            $notes[] = 'WHAT THE LAYOUT RULE CANNOT DO, which is a statement about the rule rather than about the';
            $notes[] = 'vans — a tighter pack would handle these:';
            foreach ($overflowNotes as $note) {
                $notes[] = '  '.$note;
            }
        }

        $yaml = implode("\n", $lines)."\n".implode("\n\n", $placements)."\n";
        if ([] !== $notes) {
            $yaml .= "\nnotes: |\n".implode("\n", array_map(static fn (string $n): string => '  '.$n, $notes))."\n";
        }

        return $yaml;
    }

    private static function number(float $value): string
    {
        $formatted = rtrim(rtrim(sprintf('%.4F', $value), '0'), '.');

        return '' === $formatted || '-0' === $formatted ? '0' : $formatted;
    }
}
